services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: DOW-Bot-Builder
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: pnpm run build && pnpm run start
  mongo:
    image: mongo:latest
    container_name: DOW-Bot-Mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: DOWbot
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local
